### ISSUE TITLE
Error: No such command 'render'.

### ISSUE THREAD

**Issue by meabed** [denisart/graphql2python#23]
Hi,
Thank you for building this, very useful!
while following the docs and running `render` gives an error: 
```
graphql2python render --config ./graphql2python.yaml

Error: No such command 'render'.
```

But running `generate` works fine: 
```
graphql2python generate --config ./graphql2python.yaml
```

**Comment by denisart** [comment]
Hello, thank for your comment.

Of course, this is a mistake.
In the future I will release updates to the package and fix all errors in the documentation.

**Comment by denisart** [comment]
The problem solved in https://github.com/denisart/graphql2python/pull/25
This fix will go in next release,
